using System;
using Chords.Core.Attributes;

namespace Chords.Core.Models
{
	//P: Perfect, m: Minor, M: Major, d: Diminished, A: Augmented
	public enum Interval
    {
        [Descriptor("1")]
        P1, 
        [Descriptor("4")]
        P4, 
        [Descriptor("5")]
        P5, 
        [Descriptor("8")]
        P8, 
        [Descriptor("11")]
        P11, 
        [Descriptor("12")]
        P12, 
        [Descriptor("15")]
        P15,
        [Descriptor("m2")]
        m2, 
        [Descriptor("m3")]
        m3, 
        [Descriptor("m6")]
        m6, 
        [Descriptor("m7")]
        m7, 
        [Descriptor("m9")]
        m9, 
        [Descriptor("m10")]
        m10, 
        [Descriptor("m13")]
        m13, 
        [Descriptor("m14")]
        m14, 
		[Descriptor("2")]
		M2,
		[Descriptor("3")]
		M3,
		[Descriptor("6")]
		M6,
		[Descriptor("7")]
		M7,
		[Descriptor("9")]
		M9,
		[Descriptor("10")]
		M10,
		[Descriptor("13")]
		M13,
		[Descriptor("14")]
		M14,
		[Descriptor("b2")]
		d2,
		[Descriptor("b3")]
		d3,
		[Descriptor("b4")]
		d4,
		[Descriptor("b5")]
		d5,
		[Descriptor("b6")]
		d6,
		[Descriptor("b7")]
		d7,
		[Descriptor("b8")]
		d8,
		[Descriptor("b9")]
		d9,
		[Descriptor("b10")]
		d10,
		[Descriptor("b11")]
		d11,
		[Descriptor("b12")]
		d12,
		[Descriptor("b13")]
		d13,
		[Descriptor("b14")]
		d14,
		[Descriptor("b15")]
		d15,
        [Descriptor("#1")]
        A1, 
        [Descriptor("#2")]
        A2, 
        [Descriptor("#3")]
        A3, 
        [Descriptor("#4")]
        A4, 
        [Descriptor("#5")]
        A5, 
        [Descriptor("#6")]
        A6, 
        [Descriptor("#7")]
        A7, 
        [Descriptor("#8")]
        A8, 
        [Descriptor("#9")]
        A9, 
        [Descriptor("#10")]
        A10, 
        [Descriptor("#11")]
        A11, 
        [Descriptor("#12")]
        A12, 
        [Descriptor("#13")]
        A13, 
        [Descriptor("#14")]
        A14, 
        [Descriptor("#15")]
        A15
    }
}
