#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Chords.Android.Views
{
using System;

#line 1 "FavoriteChordsView.cshtml"
using System.Collections.Generic;

#line default
#line hidden
using System.Linq;
using System.Text;

#line 2 "FavoriteChordsView.cshtml"
using Chords.Android.Models;

#line default
#line hidden

#line 3 "FavoriteChordsView.cshtml"
using Chords.Core.Extensions;

#line default
#line hidden


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class FavoriteChordsView : PortableRazor.ViewBase
{

#line hidden

#line 5 "FavoriteChordsView.cshtml"
public FavoriteChordsModel Model { get; set; }

#line default
#line hidden


public override void Execute()
{
WriteLiteral("<!DOCTYPE html>\n<html>\n<head>\n    <!--link rel=\"stylesheet\" href=\"jquery.mobile-1" +
".4.5.min.css\" /-->\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"style.css\"");

WriteLiteral(" />\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"bootstrap.min.css\"");

WriteLiteral(" />\n</head>\n<body>\n    <nav");

WriteLiteral(" class=\"navbar navbar-inverse navbar-fixed-top\"");

WriteLiteral(">\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\n            <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"navbar-toggle\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-target=\".navbar-collapse\"");

WriteLiteral(">\n                    <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Toggle navigation</span>\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\n                </button>\n                <span");

WriteLiteral(" class=\"navbar-brand\"");

WriteLiteral(">Favourite chords</span>\n            </div>\n                \n            <div");

WriteLiteral(" class=\"navbar-collapse collapse\"");

WriteLiteral(">\n                <ul");

WriteLiteral(" class=\"nav navbar-nav\"");

WriteLiteral(">\n                    <li><a");

WriteLiteral(" href=\"hybrid:ShowChord\"");

WriteLiteral(">Show chord chart</a></li>\n                    <li><a");

WriteLiteral(" href=\"hybrid:FindChord\"");

WriteLiteral(">Find chord name</a></li>\n                    <li><a");

WriteLiteral(" href=\"hybrid:FavoriteChords\"");

WriteLiteral(">Favourite chords</a></li>\n                    <li><a");

WriteLiteral(" href=\"hybrid:Circle\"");

WriteLiteral(">Circle of fifths</a></li>\n                    <li><a");

WriteLiteral(" href=\"hybrid:Settings\"");

WriteLiteral(">Settings</a></li>\n                </ul>\n            </div>\n        </div>\n    </" +
"nav>\n    <script");

WriteLiteral(" src=\"jquery.min.js\"");

WriteLiteral("></script>\n    <script");

WriteLiteral(" src=\"jquery.mobile-1.4.5.min.js\"");

WriteLiteral("></script>\n    <script");

WriteLiteral(" src=\"bootstrap.min.js\"");

WriteLiteral("></script>\n    <div");

WriteLiteral(" class=\"col-xs-12 col-sm-12 col-md-12 col-lg-12 main-content\"");

WriteLiteral(">\n\n        <!-- Main content start -->\n        <div");

WriteLiteral(" id=\"layouts\"");

WriteLiteral(" class=\"animate-bottom\"");

WriteLiteral(">\n");


#line 44 "FavoriteChordsView.cshtml"
		

#line default
#line hidden

#line 44 "FavoriteChordsView.cshtml"
         if (Model.Chords.Any())
		{
	        foreach(var kvp in Model.Chords)
	        {


#line default
#line hidden
WriteLiteral("\t\t\t\t<div");

WriteLiteral(" class=\"col-xs-12 col-sm-12 col-md-12 col-lg-12\"");

WriteLiteral(">\n\t                <h2>");


#line 49 "FavoriteChordsView.cshtml"
                   Write(kvp.Key.Symbols[0]);


#line default
#line hidden
WriteLiteral("</h2>\n\n");


#line 51 "FavoriteChordsView.cshtml"
	                

#line default
#line hidden

#line 51 "FavoriteChordsView.cshtml"
                     foreach(var layout in kvp.Value)
	                {
	                    var positions = string.Join(",", layout.IntPositions.Select(i => i.ToString()).ToArray());



#line default
#line hidden
WriteLiteral("\t                    <div");

WriteLiteral(" class=\"chord-layout\"");

WriteLiteral(" data-root=\"");


#line 55 "FavoriteChordsView.cshtml"
                                                         Write(kvp.Key.Root.ToString(Model.conv));


#line default
#line hidden
WriteLiteral("\"");

WriteLiteral(" data-chordtype=\"");


#line 55 "FavoriteChordsView.cshtml"
                                                                                                               Write(kvp.Key.ChordType.ToDescription());


#line default
#line hidden
WriteLiteral("\"");

WriteLiteral(" data-favorite=\"");


#line 55 "FavoriteChordsView.cshtml"
                                                                                                                                                                    Write(layout.Favorite);


#line default
#line hidden
WriteLiteral("\"");

WriteLiteral(" data-positions=\"");


#line 55 "FavoriteChordsView.cshtml"
                                                                                                                                                                                                       Write(positions);


#line default
#line hidden
WriteLiteral("\"");

WriteAttribute ("onclick", " onclick=\"", "\""
, Tuple.Create<string,object,bool> ("", "playChord(\'", true)

#line 55 "FavoriteChordsView.cshtml"
                                                                                                                                                                                                     , Tuple.Create<string,object,bool> ("", positions

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", "\');", true)
);
WriteLiteral(">\n");

WriteLiteral("\t                        ");


#line 56 "FavoriteChordsView.cshtml"
                        Write(layout.Schema);


#line default
#line hidden
WriteLiteral("\n\t                    </div>\n");


#line 58 "FavoriteChordsView.cshtml"
	                }


#line default
#line hidden
WriteLiteral("\t\t\t\t</div>\n");

WriteLiteral("\t\t\t\t<div");

WriteLiteral(" class=\"col-xs-12 col-sm-12 col-md-12 col-lg-12\"");

WriteLiteral(">\n\t\t\t\t    <hr />\n\t\t\t\t</div>\n");


#line 63 "FavoriteChordsView.cshtml"
	        }
		}
		else
		{


#line default
#line hidden
WriteLiteral("\t\t\t<div");

WriteLiteral(" class=\"col-xs-12 col-sm-12 col-md-12 col-lg-12\"");

WriteLiteral("  style=\"text-align: center;\"");

WriteLiteral(">\n\t\t\t\tYou have no favourite chord layouts. <br />\n\t\t\t\tTap and hold a chord layout" +
" to add it to favourites.  \n\t\t\t</div>\n");


#line 71 "FavoriteChordsView.cshtml"
		}


#line default
#line hidden
WriteLiteral("        </div>\n        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
            $('#loader').hide();
            $('#layouts').show();
            function playChord(positions) {
                $.ajax({
                    url: 'hybrid:PlayChord',
                    type: 'get',
                    data: {
                        positions: positions
                    }
                });
            }
            function setFavorite(selector, value) {
                $(selector).attr('data-favorite', value);
            }
            $(function(){
			    $('.ui-loader').hide();
                $.event.special.tap.tapholdThreshold = 300;
                $.event.special.tap.emitTapOnTaphold = false;
                $('.chord-layout').bind('taphold', function(){				    
				    var root = $(this).attr('data-root');
				    var type = $(this).attr('data-chordtype');
                    var positions = $(this).attr('data-positions');
                    var favorite = $(this).attr('data-favorite') == ""True"";

                    $.ajax({
                        url: favorite ? 'hybrid:RemoveFromFavorites' : 'hybrid:AddToFavorites',
                        type: 'get',
                        data: {
                            root: root,
                            type: type,
                            conv: '");


#line 104 "FavoriteChordsView.cshtml"
                              Write(Model.conv);


#line default
#line hidden
WriteLiteral(@"',
                            positions: positions
                        }
                    });
                });
            });
        </script>			
        <!-- Main content end -->   

    </div>
    <hr />
    <footer>
        <p>&copy; 2017 - Tomáš Němec</p>
    </footer>
</body>
</html>

");

}
}
}
#pragma warning restore 1591
