#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Chords.Android.Views
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class ShowChordLayoutsView : PortableRazor.ViewBase
{

#line hidden

#line 2 "ShowChordLayoutsView.cshtml"
public Chords.Android.Models.ShowChordLayoutsModel Model { get; set; }

#line default
#line hidden


public override void Execute()
{

#line 3 "ShowChordLayoutsView.cshtml"
  
    var otherSymbols = Model.ChordDecorator.Symbols.Skip(1);


#line default
#line hidden
WriteLiteral("\n<!DOCTYPE html>\n<html>\n<head>\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"style.css\"");

WriteLiteral(" />\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"bootstrap.min.css\"");

WriteLiteral(" />\n</head>\n<body>\n    <nav");

WriteLiteral(" class=\"navbar navbar-inverse navbar-fixed-top\"");

WriteLiteral(">\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\n            <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"navbar-toggle\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-target=\".navbar-collapse\"");

WriteLiteral(">\n                    <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Toggle navigation</span>\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\n                </button>\n                <span");

WriteLiteral(" class=\"navbar-brand\"");

WriteLiteral(">Guitar Chords</span>\n            </div>\n                \n            <div");

WriteLiteral(" class=\"navbar-collapse collapse\"");

WriteLiteral(">\n                <ul");

WriteLiteral(" class=\"nav navbar-nav\"");

WriteLiteral(">\n                    <li><a");

WriteLiteral(" href=\"hybrid:ShowChord\"");

WriteLiteral(">Show chord</a></li>\n                    <li><a");

WriteLiteral(" href=\"hybrid:FindChord\"");

WriteLiteral(">Find chord</a></li>\n                </ul>\n            </div>\n        </div>\n    " +
"</nav>\n    <script");

WriteLiteral(" src=\"jquery.min.js\"");

WriteLiteral("></script>\n    <script");

WriteLiteral(" src=\"bootstrap.min.js\"");

WriteLiteral("></script>\n    <div");

WriteLiteral(" class=\"col-xs-12 col-sm-12 col-md-12 col-lg-12\"");

WriteLiteral(">\n\n        <!-- Main content start -->\n        <h2>");


#line 38 "ShowChordLayoutsView.cshtml"
       Write(Model.ChordDecorator.Symbols[0]);


#line default
#line hidden
WriteLiteral("</h2>\n\n");


#line 40 "ShowChordLayoutsView.cshtml"
        

#line default
#line hidden

#line 40 "ShowChordLayoutsView.cshtml"
         if (otherSymbols.Any())
        {


#line default
#line hidden
WriteLiteral("            <h4>Other symbols:</h4>\n");


#line 43 "ShowChordLayoutsView.cshtml"
            foreach(var otherSymbol in otherSymbols)
            {


#line default
#line hidden
WriteLiteral("                <span>");


#line 45 "ShowChordLayoutsView.cshtml"
                 Write(otherSymbol);


#line default
#line hidden
WriteLiteral("</span>\n");


#line 46 "ShowChordLayoutsView.cshtml"
            }
        }


#line default
#line hidden
WriteLiteral("        <h4>Chord intervals:</h4>\n        <p>\n");


#line 50 "ShowChordLayoutsView.cshtml"
        

#line default
#line hidden

#line 50 "ShowChordLayoutsView.cshtml"
         foreach(var interval in Model.ChordDecorator.Intervals)
        {


#line default
#line hidden
WriteLiteral("            <span>");


#line 52 "ShowChordLayoutsView.cshtml"
             Write(interval);


#line default
#line hidden
WriteLiteral("</span>\n");


#line 53 "ShowChordLayoutsView.cshtml"
        }


#line default
#line hidden
WriteLiteral("        </p>\n\n        <h4>Chord notes:</h4>\n        <p>\n");


#line 58 "ShowChordLayoutsView.cshtml"
        

#line default
#line hidden

#line 58 "ShowChordLayoutsView.cshtml"
         foreach(var note in Model.ChordDecorator.Notes)
        {


#line default
#line hidden
WriteLiteral("            <span>");


#line 60 "ShowChordLayoutsView.cshtml"
             Write(note);


#line default
#line hidden
WriteLiteral("</span>\n");


#line 61 "ShowChordLayoutsView.cshtml"
        }


#line default
#line hidden
WriteLiteral("        </p>\n        <div");

WriteLiteral(" id=\"error\"");

WriteLiteral(" class=\"error\"");

WriteLiteral(">");


#line 63 "ShowChordLayoutsView.cshtml"
                                 Write(Model.Error);


#line default
#line hidden
WriteLiteral("</div>\n        <div");

WriteLiteral(" id=\"loader\"");

WriteLiteral("></div>\n        <div");

WriteLiteral(" id=\"layouts\"");

WriteLiteral(" class=\"animate-bottom\"");

WriteLiteral(">\n");


#line 66 "ShowChordLayoutsView.cshtml"
        

#line default
#line hidden

#line 66 "ShowChordLayoutsView.cshtml"
         if (Model.Layouts != null)
        {


#line default
#line hidden
WriteLiteral("            <h4>Chord layouts:</h4>\n");

WriteLiteral("            <p>\n");

WriteLiteral("                ");


#line 70 "ShowChordLayoutsView.cshtml"
           Write(Model.Layouts.Length);


#line default
#line hidden
WriteLiteral(" results\n");


#line 71 "ShowChordLayoutsView.cshtml"
                

#line default
#line hidden

#line 71 "ShowChordLayoutsView.cshtml"
                 foreach(var layout in Model.Layouts)
                {


#line default
#line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"col-xs-6 col-sm-4 col-md-3 col-lg-2 chord-layout\"");

WriteLiteral(">\n");


#line 74 "ShowChordLayoutsView.cshtml"
                        

#line default
#line hidden

#line 74 "ShowChordLayoutsView.cshtml"
                         if (layout.Complete)
                        {


#line default
#line hidden
WriteLiteral("                            <div");

WriteLiteral(" class=\"chordlayout\"");

WriteLiteral(">");


#line 76 "ShowChordLayoutsView.cshtml"
                                                 Write(layout.ToHtmlString());


#line default
#line hidden
WriteLiteral("</div>\n");


#line 77 "ShowChordLayoutsView.cshtml"
                        }
                        else
                        {


#line default
#line hidden
WriteLiteral("                            <div");

WriteLiteral(" class=\"chordlayout incomplete\"");

WriteLiteral(">");


#line 80 "ShowChordLayoutsView.cshtml"
                                                            Write(layout.ToHtmlString());


#line default
#line hidden
WriteLiteral("</div>\n");


#line 81 "ShowChordLayoutsView.cshtml"
                        }


#line default
#line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"chordschema\"");

WriteLiteral(">\n");

WriteLiteral("                        ");


#line 83 "ShowChordLayoutsView.cshtml"
                    Write(layout.Schema);


#line default
#line hidden
WriteLiteral("\n                        </div>\n                    </div>\n");


#line 86 "ShowChordLayoutsView.cshtml"
                }


#line default
#line hidden
WriteLiteral("            </p>\n");

WriteLiteral("            <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\n                $(\'#loader\').hide();\n                $(\'#layouts\').show();\n    " +
"        </script>\n");


#line 92 "ShowChordLayoutsView.cshtml"
        }


#line default
#line hidden
WriteLiteral("    <!-- Main content end -->   \n\n    </div>\n    <hr />\n    <footer>\n        <p>&" +
"copy; 2017 - Tomáš Němec</p>\n    </footer>\n</body>\n</html>\n");

}
}
}
#pragma warning restore 1591
